- type: gameMapPool
  id: EvinDefaultMapPool
  maps:
  - EvinDelta
  - EvinSilly
  - Pilgrim
  - EvinAtlas
  - EvinBagel
  - EvinBox
  - EvinCluster
  - EvinCore
  - Fland
  - Marathon
  - Meta
  - EvinOmega
  - EvinOrigin
  - EvinSaltern
  - Packed
  - Reach
