- type: job
  id: Blueshield
  name: job-name-blueshield
  description: job-description-blueshield
  playTimeTracker: JobBlueshield
  whitelisted: true
  requirements:
    - !type:DepartmentTimeRequirement
      department: Security
      time: 72000
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 36000
    - !type:OverallPlaytimeRequirement
      time: 100000
  startingGear: BlueshieldGear
  icon: "JobIconBlueshield"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  access:
  - Blueshield
  - Command
  - Bar
  - Service
  - Maintenance
  - Janitor
  - Theatre
  - Kitchen
  - Chapel
  - Hydroponics
  - External
  - Chemistry
  - Engineering
  - Research
  - Detective
  - Salvage
  - Security
  - Brig
  - Cargo
  - Atmospherics
  - Cargo
  - Medical
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]

- type: startingGear
  id: BlueshieldGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitBlueshield
    shoes: ClothingShoesBootsCombatFilled
    eyes: ClothingEyesGlassesBlueshield
    outerClothing: ClothingOuterArmorBulletproof
    id: BlueshieldPDA
    ears: ClothingHeadsetAltCommand
    pocket1: WeaponRevolverMateba
    pocket2: CrowbarRed
    belt: ClothingBeltSecurityFilled
    gloves: ClothingHandsGlovesCombat
